"""empty message

Revision ID: 21e054ecfb91
Revises: d211feb88328
Create Date: 2023-02-25 16:26:34.384408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e054ecfb91'
down_revision = 'd211feb88328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_constraint('content_facebook_key', type_='unique')
        batch_op.drop_constraint('content_image_link_key', type_='unique')
        batch_op.drop_constraint('content_instagram_key', type_='unique')
        batch_op.drop_constraint('content_location_city_key', type_='unique')
        batch_op.drop_constraint('content_location_coordinates_key', type_='unique')
        batch_op.drop_constraint('content_location_street_key', type_='unique')
        batch_op.drop_constraint('content_phone_number_key', type_='unique')
        batch_op.drop_constraint('content_tiktok_key', type_='unique')
        batch_op.drop_constraint('content_twitter_key', type_='unique')
        batch_op.drop_column('tiktok')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiktok', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('content_twitter_key', ['twitter'])
        batch_op.create_unique_constraint('content_tiktok_key', ['tiktok'])
        batch_op.create_unique_constraint('content_phone_number_key', ['phone_number'])
        batch_op.create_unique_constraint('content_location_street_key', ['location_street'])
        batch_op.create_unique_constraint('content_location_coordinates_key', ['location_coordinates'])
        batch_op.create_unique_constraint('content_location_city_key', ['location_city'])
        batch_op.create_unique_constraint('content_instagram_key', ['instagram'])
        batch_op.create_unique_constraint('content_image_link_key', ['image_link'])
        batch_op.create_unique_constraint('content_facebook_key', ['facebook'])

    # ### end Alembic commands ###
