"""empty message

Revision ID: 41618187da5f
Revises: 42a8381acc72
Create Date: 2023-02-03 18:55:03.827093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41618187da5f'
down_revision = '42a8381acc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branding', sa.Column('color_bg1', sa.String(length=100), nullable=False))
    op.add_column('branding', sa.Column('color_bg2', sa.String(length=100), nullable=False))
    op.add_column('branding', sa.Column('color_font1', sa.String(length=100), nullable=False))
    op.add_column('branding', sa.Column('color_hover1', sa.String(length=100), nullable=False))
    op.drop_column('branding', 'color')
    op.add_column('content', sa.Column('instagram', sa.String(length=100), nullable=True))
    op.add_column('content', sa.Column('twitter', sa.String(length=100), nullable=True))
    op.add_column('content', sa.Column('facebook', sa.String(length=100), nullable=True))
    op.add_column('content', sa.Column('tiktok', sa.String(length=100), nullable=True))
    op.add_column('content', sa.Column('location', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'content', ['instagram'])
    op.create_unique_constraint(None, 'content', ['location'])
    op.create_unique_constraint(None, 'content', ['tiktok'])
    op.create_unique_constraint(None, 'content', ['facebook'])
    op.create_unique_constraint(None, 'content', ['twitter'])
    op.add_column('food', sa.Column('allergens', sa.String(length=250), nullable=False))
    op.add_column('web', sa.Column('phone_number', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'web', ['phone_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'web', type_='unique')
    op.drop_column('web', 'phone_number')
    op.drop_column('food', 'allergens')
    op.drop_constraint(None, 'content', type_='unique')
    op.drop_constraint(None, 'content', type_='unique')
    op.drop_constraint(None, 'content', type_='unique')
    op.drop_constraint(None, 'content', type_='unique')
    op.drop_constraint(None, 'content', type_='unique')
    op.drop_column('content', 'location')
    op.drop_column('content', 'tiktok')
    op.drop_column('content', 'facebook')
    op.drop_column('content', 'twitter')
    op.drop_column('content', 'instagram')
    op.add_column('branding', sa.Column('color', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('branding', 'color_hover1')
    op.drop_column('branding', 'color_font1')
    op.drop_column('branding', 'color_bg2')
    op.drop_column('branding', 'color_bg1')
    # ### end Alembic commands ###
