"""empty message

Revision ID: 8f42e730faa7
Revises: 3f8855abf1cc
Create Date: 2023-02-15 17:53:49.214230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f42e730faa7'
down_revision = '3f8855abf1cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['phone_number'])

    with op.batch_alter_table('web', schema=None) as batch_op:
        batch_op.drop_constraint('web_phone_number_key', type_='unique')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('web_phone_number_key', ['phone_number'])

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
