"""empty message

Revision ID: d211feb88328
Revises: 90ef29fb3c8f
Create Date: 2023-02-25 15:33:03.877223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd211feb88328'
down_revision = '90ef29fb3c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiktok', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['tiktok'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('tiktok')

    # ### end Alembic commands ###
